### PR TITLE
Feature/201704 minor changes

### PR DESCRIPTION
**Pull request by teelee7133**
Bug fixes:

- fix success story image in dialog box
- fix mobile nav menu
- update newsletter signup functionality
- cleanup/fix footer social links
- update donation dialog box

Additionally:

- add django-extensions for debugging
- add management function to copy public image/files to local enviroment, so remove dependency to aws s3 in development environment

### CODE REVIEW

**Comment by lili2311** [comment]
As per slack chat looks good, but the new template seems to be missing some header styling and logo https://testseoapp1.herokuapp.com/newsletter/thank_you/

**Comment by teelee7133** [comment]
Thanks for looking at it!  I added a logo placeholder, and removed the teal background.  An example result can be viewed in https://testseoapp1.herokuapp.com/newsletter/thank_you/

**Comment by lili2311** [comment]
👍

**Comment by lili2311** [comment]
Should I merge?

**Comment by teelee7133** [comment]
yes please!!

**Pull request merged**
